config/routes.rb
DemoApp::Application.routes.draw do

  
   root :to => 'sessions#new'
   resources :users
   
   resource :session
   match '/login'=>"sessions#new" , :as=>"login"
   match '/logout'=>"sessions#destroy" , :as=>"logout"
   match '/user_signin/:user'=>"sessions#login" , :as=>"user_signin"

end

app/models/user.rb
class User < ActiveRecord::Base
   attr_accessible :email , :password
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :current_user

  def current_user
      if session[:user_id].present?
        User.find(session[:user_id])
      end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create 
         user=User.where("email=? AND password=?",params[:email],params[:password]).first 
         if user.present?   
            session[:user_id]=user.id
              redirect_to user_path(session[:user_id]) , :notice=>"Logged in successfully"
         else
            flash.now[:alert]="Invalid login/password combination"
            render :action => 'new'
         end
    end
    def destroy 
          reset_session
          redirect_to root_path , :notice=>"you successfully logout"
    end
    def login
          
         user=User.find(params[:user])       
         
         if user.present?   
            session[:user_id]=user.id
          
              redirect_to user_path(session[:user_id]) , :notice=>"Logged in successfully"
         else
            
            flash.now[:alert]="Invalid login/password combination"
            render :action => 'new'
         end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def index
end
def new
  @user=User.new 
end
def create

  @user=User.create(params[:user])
    if @user.save
        redirect_to user_signin_path(:user=>@user.id) 
    else
        flash ="Email already taken"      
        render :new
    end
end 
def show
   
  if current_user.present?  
    @user=User.find(session[:user_id])
  else
    redirect_to new_session_path
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<div id="out">
  <div class="head">
    <h4>Register</h4>
  </div>
  
<%=form_for @user ,:html=>{:onsubmit=>"return validate(this.user_email,this.user_password);",:name=>"myForm"} do |f|%>
  <div class="field">
     <span class="b1">    
      <%=f.label :email%><span style="color:red;">*</span>
     </span>
    <%=f.text_field :email, :class=> "t1",:size=>"20" %>
  </div>
  <div class="field">
      <span>
      <%=f.label :password%><span style="color:red;">*</span>
      </span>
      <%=f.password_field :password,:class=> "t1" ,:size=>"20" %>
  </div>
  <div class="actions">
    <%= f.submit 'Sign up',:class=>"t2"%>
    <%= link_to "Sign in" ,new_session_path%>
  </div>
<%end%>
</div>

app/views/users/new.html.erb
<%=render 'form'%>
<% if @user.errors.present? %>
<%=@user.errors.full_messages%>
<% end %>

app/views/users/show.html.erb
<%=link_to :sign_out , session_path(@user) , :method => :delete %>
<br/><br/>
Email:<%=@user.email%><br/>
Password:<%=@user.password%>